import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/Banner';
import Background from '../components/Banner/Background';
import BuyPet from '../components/BuyPet';
import OneMoreFriend from '../components/SubBanner/OneMoreFriend';
import Adoption from '../components/SubBanner/Adoption';
import PetSeller from '../components/PetSeller';
import PetKnowledge from '../components/PetKnowledge';
import BuyProduct from '../components/BuyProduct';
import { loadDogs } from '../Helper/access';

export default function Home({ data }) {
  const dogs = data.dogs;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="relative">
        <Background />
        <Banner />
      </header>

      <main className="bg-white w-[100vw] -ml-[16px] laptop:-ml-[60px] desktop:-ml-[130px] mt-0 min-h-[1000px]">
        <div className="subMain mx-4 laptop:mx-[60px] desktop:mx-[130px]">
          <BuyPet dogs={dogs} />
          <OneMoreFriend className="mt-[60px]" />
          <BuyProduct />
          <PetSeller />
          <Adoption />
          <PetKnowledge />
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const data = await loadDogs({
    page: 1,
    limit: 15,
  });
  return {
    props: {
      data,
    },
  };
}
